import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Banner from './components/banner'
import Help from './components/help'
import Short_intro from './components/short_intro'


export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
      <meta name="viewport" content="width=device-width, initial-scale=1" />
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
      <div className='bg-gradient-to-b from-pink-100 to-white p-4 sm:p-10'>
        <Banner/>
        <div className='p-2'>
        <Short_intro/>
        </div>
      </div>
      <Help/>
      </main>
    </div>
  )
}
